name: "pre-release"

on:
  push:
    branches:
      - "main"

permissions:
  id-token: "write"
  contents: "write"
  packages: "write"
  pull-requests: "read"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1.0.5

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: liberica
        java-version: 8.0.392+9
        java-package: jdk+fx

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper

    - name: Execute Gradle build
      run: ./gradlew shadowJar -Pplatform=windows
    - name: Execute Gradle build
      run: ./gradlew shadowJar -Pplatform=linux

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Latest Development Build"
        files: |
          dist/*
